// Decompiled with JetBrains decompiler
// Type: TinyZoo.FontSet_Hiragana_Hiragana
// Assembly: LetsBuildAZoo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DEB7467C-E857-4369-A6B7-78A1E0037E5E
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Let's Build a Zoo Demo\LetsBuildAZoo.exe

using Microsoft.Xna.Framework;
using SEngine;
using System.Collections.Generic;

namespace TinyZoo
{
  internal class FontSet_Hiragana_Hiragana : FontBase
  {
    public override void CreateFontSet(
      Dictionary<char, SpringFontCharacter> FontDictionary)
    {
      SpringFontCharacter springFontCharacter1 = new SpringFontCharacter('\u3040', new Rectangle(1, 1, 7, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter1.Character, springFontCharacter1);
      SpringFontCharacter springFontCharacter2 = new SpringFontCharacter('ぁ', new Rectangle(9, 1, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter2.Character, springFontCharacter2);
      SpringFontCharacter springFontCharacter3 = new SpringFontCharacter('あ', new Rectangle(21, 1, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter3.Character, springFontCharacter3);
      SpringFontCharacter springFontCharacter4 = new SpringFontCharacter('ぃ', new Rectangle(38, 1, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter4.Character, springFontCharacter4);
      SpringFontCharacter springFontCharacter5 = new SpringFontCharacter('い', new Rectangle(50, 1, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter5.Character, springFontCharacter5);
      SpringFontCharacter springFontCharacter6 = new SpringFontCharacter('ぅ', new Rectangle(67, 1, 10, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter6.Character, springFontCharacter6);
      SpringFontCharacter springFontCharacter7 = new SpringFontCharacter('う', new Rectangle(78, 1, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter7.Character, springFontCharacter7);
      SpringFontCharacter springFontCharacter8 = new SpringFontCharacter('ぇ', new Rectangle(90, 1, 10, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter8.Character, springFontCharacter8);
      SpringFontCharacter springFontCharacter9 = new SpringFontCharacter('え', new Rectangle(101, 1, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter9.Character, springFontCharacter9);
      SpringFontCharacter springFontCharacter10 = new SpringFontCharacter('ぉ', new Rectangle(116, 1, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter10.Character, springFontCharacter10);
      SpringFontCharacter springFontCharacter11 = new SpringFontCharacter('お', new Rectangle(129, 1, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter11.Character, springFontCharacter11);
      SpringFontCharacter springFontCharacter12 = new SpringFontCharacter('か', new Rectangle(146, 1, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter12.Character, springFontCharacter12);
      SpringFontCharacter springFontCharacter13 = new SpringFontCharacter('が', new Rectangle(164, 1, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter13.Character, springFontCharacter13);
      SpringFontCharacter springFontCharacter14 = new SpringFontCharacter('き', new Rectangle(181, 1, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter14.Character, springFontCharacter14);
      SpringFontCharacter springFontCharacter15 = new SpringFontCharacter('ぎ', new Rectangle(196, 1, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter15.Character, springFontCharacter15);
      SpringFontCharacter springFontCharacter16 = new SpringFontCharacter('く', new Rectangle(213, 1, 10, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter16.Character, springFontCharacter16);
      SpringFontCharacter springFontCharacter17 = new SpringFontCharacter('ぐ', new Rectangle(1, 20, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter17.Character, springFontCharacter17);
      SpringFontCharacter springFontCharacter18 = new SpringFontCharacter('け', new Rectangle(16, 20, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter18.Character, springFontCharacter18);
      SpringFontCharacter springFontCharacter19 = new SpringFontCharacter('げ', new Rectangle(33, 20, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter19.Character, springFontCharacter19);
      SpringFontCharacter springFontCharacter20 = new SpringFontCharacter('こ', new Rectangle(51, 20, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter20.Character, springFontCharacter20);
      SpringFontCharacter springFontCharacter21 = new SpringFontCharacter('ご', new Rectangle(64, 20, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter21.Character, springFontCharacter21);
      SpringFontCharacter springFontCharacter22 = new SpringFontCharacter('さ', new Rectangle(81, 20, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter22.Character, springFontCharacter22);
      SpringFontCharacter springFontCharacter23 = new SpringFontCharacter('ざ', new Rectangle(96, 20, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter23.Character, springFontCharacter23);
      SpringFontCharacter springFontCharacter24 = new SpringFontCharacter('し', new Rectangle(114, 20, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter24.Character, springFontCharacter24);
      SpringFontCharacter springFontCharacter25 = new SpringFontCharacter('じ', new Rectangle(126, 20, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter25.Character, springFontCharacter25);
      SpringFontCharacter springFontCharacter26 = new SpringFontCharacter('す', new Rectangle(139, 20, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter26.Character, springFontCharacter26);
      SpringFontCharacter springFontCharacter27 = new SpringFontCharacter('ず', new Rectangle(157, 20, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter27.Character, springFontCharacter27);
      SpringFontCharacter springFontCharacter28 = new SpringFontCharacter('せ', new Rectangle(175, 20, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter28.Character, springFontCharacter28);
      SpringFontCharacter springFontCharacter29 = new SpringFontCharacter('ぜ', new Rectangle(192, 20, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter29.Character, springFontCharacter29);
      SpringFontCharacter springFontCharacter30 = new SpringFontCharacter('そ', new Rectangle(210, 20, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter30.Character, springFontCharacter30);
      SpringFontCharacter springFontCharacter31 = new SpringFontCharacter('ぞ', new Rectangle(227, 20, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter31.Character, springFontCharacter31);
      SpringFontCharacter springFontCharacter32 = new SpringFontCharacter('た', new Rectangle(245, 20, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter32.Character, springFontCharacter32);
      SpringFontCharacter springFontCharacter33 = new SpringFontCharacter('だ', new Rectangle(1, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter33.Character, springFontCharacter33);
      SpringFontCharacter springFontCharacter34 = new SpringFontCharacter('ち', new Rectangle(18, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter34.Character, springFontCharacter34);
      SpringFontCharacter springFontCharacter35 = new SpringFontCharacter('ぢ', new Rectangle(35, 39, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter35.Character, springFontCharacter35);
      SpringFontCharacter springFontCharacter36 = new SpringFontCharacter('っ', new Rectangle(53, 39, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter36.Character, springFontCharacter36);
      SpringFontCharacter springFontCharacter37 = new SpringFontCharacter('つ', new Rectangle(65, 39, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter37.Character, springFontCharacter37);
      SpringFontCharacter springFontCharacter38 = new SpringFontCharacter('づ', new Rectangle(80, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter38.Character, springFontCharacter38);
      SpringFontCharacter springFontCharacter39 = new SpringFontCharacter('て', new Rectangle(97, 39, 15, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter39.Character, springFontCharacter39);
      SpringFontCharacter springFontCharacter40 = new SpringFontCharacter('で', new Rectangle(113, 39, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter40.Character, springFontCharacter40);
      SpringFontCharacter springFontCharacter41 = new SpringFontCharacter('と', new Rectangle(131, 39, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter41.Character, springFontCharacter41);
      SpringFontCharacter springFontCharacter42 = new SpringFontCharacter('ど', new Rectangle(143, 39, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter42.Character, springFontCharacter42);
      SpringFontCharacter springFontCharacter43 = new SpringFontCharacter('な', new Rectangle(158, 39, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter43.Character, springFontCharacter43);
      SpringFontCharacter springFontCharacter44 = new SpringFontCharacter('に', new Rectangle(176, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter44.Character, springFontCharacter44);
      SpringFontCharacter springFontCharacter45 = new SpringFontCharacter('ぬ', new Rectangle(193, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter45.Character, springFontCharacter45);
      SpringFontCharacter springFontCharacter46 = new SpringFontCharacter('ね', new Rectangle(210, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter46.Character, springFontCharacter46);
      SpringFontCharacter springFontCharacter47 = new SpringFontCharacter('の', new Rectangle(227, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter47.Character, springFontCharacter47);
      SpringFontCharacter springFontCharacter48 = new SpringFontCharacter('は', new Rectangle(244, 39, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter48.Character, springFontCharacter48);
      SpringFontCharacter springFontCharacter49 = new SpringFontCharacter('ば', new Rectangle(1, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter49.Character, springFontCharacter49);
      SpringFontCharacter springFontCharacter50 = new SpringFontCharacter('ぱ', new Rectangle(19, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter50.Character, springFontCharacter50);
      SpringFontCharacter springFontCharacter51 = new SpringFontCharacter('ひ', new Rectangle(37, 58, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter51.Character, springFontCharacter51);
      SpringFontCharacter springFontCharacter52 = new SpringFontCharacter('び', new Rectangle(54, 58, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter52.Character, springFontCharacter52);
      SpringFontCharacter springFontCharacter53 = new SpringFontCharacter('ぴ', new Rectangle(71, 58, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter53.Character, springFontCharacter53);
      SpringFontCharacter springFontCharacter54 = new SpringFontCharacter('ふ', new Rectangle(88, 58, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter54.Character, springFontCharacter54);
      SpringFontCharacter springFontCharacter55 = new SpringFontCharacter('ぶ', new Rectangle(105, 58, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter55.Character, springFontCharacter55);
      SpringFontCharacter springFontCharacter56 = new SpringFontCharacter('ぷ', new Rectangle(122, 58, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter56.Character, springFontCharacter56);
      SpringFontCharacter springFontCharacter57 = new SpringFontCharacter('へ', new Rectangle(139, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter57.Character, springFontCharacter57);
      SpringFontCharacter springFontCharacter58 = new SpringFontCharacter('べ', new Rectangle(157, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter58.Character, springFontCharacter58);
      SpringFontCharacter springFontCharacter59 = new SpringFontCharacter('ぺ', new Rectangle(175, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter59.Character, springFontCharacter59);
      SpringFontCharacter springFontCharacter60 = new SpringFontCharacter('ほ', new Rectangle(193, 58, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter60.Character, springFontCharacter60);
      SpringFontCharacter springFontCharacter61 = new SpringFontCharacter('ぼ', new Rectangle(210, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter61.Character, springFontCharacter61);
      SpringFontCharacter springFontCharacter62 = new SpringFontCharacter('ぽ', new Rectangle(228, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter62.Character, springFontCharacter62);
      SpringFontCharacter springFontCharacter63 = new SpringFontCharacter('ま', new Rectangle(246, 58, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter63.Character, springFontCharacter63);
      SpringFontCharacter springFontCharacter64 = new SpringFontCharacter('み', new Rectangle(261, 58, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter64.Character, springFontCharacter64);
      SpringFontCharacter springFontCharacter65 = new SpringFontCharacter('む', new Rectangle(1, 77, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter65.Character, springFontCharacter65);
      SpringFontCharacter springFontCharacter66 = new SpringFontCharacter('め', new Rectangle(18, 77, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter66.Character, springFontCharacter66);
      SpringFontCharacter springFontCharacter67 = new SpringFontCharacter('も', new Rectangle(35, 77, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter67.Character, springFontCharacter67);
      SpringFontCharacter springFontCharacter68 = new SpringFontCharacter('ゃ', new Rectangle(50, 77, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter68.Character, springFontCharacter68);
      SpringFontCharacter springFontCharacter69 = new SpringFontCharacter('や', new Rectangle(62, 77, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter69.Character, springFontCharacter69);
      SpringFontCharacter springFontCharacter70 = new SpringFontCharacter('ゅ', new Rectangle(79, 77, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter70.Character, springFontCharacter70);
      SpringFontCharacter springFontCharacter71 = new SpringFontCharacter('ゆ', new Rectangle(92, 77, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter71.Character, springFontCharacter71);
      SpringFontCharacter springFontCharacter72 = new SpringFontCharacter('ょ', new Rectangle(109, 77, 10, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter72.Character, springFontCharacter72);
      SpringFontCharacter springFontCharacter73 = new SpringFontCharacter('よ', new Rectangle(120, 77, 13, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter73.Character, springFontCharacter73);
      SpringFontCharacter springFontCharacter74 = new SpringFontCharacter('ら', new Rectangle(134, 77, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter74.Character, springFontCharacter74);
      SpringFontCharacter springFontCharacter75 = new SpringFontCharacter('り', new Rectangle(147, 77, 10, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter75.Character, springFontCharacter75);
      SpringFontCharacter springFontCharacter76 = new SpringFontCharacter('る', new Rectangle(158, 77, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter76.Character, springFontCharacter76);
      SpringFontCharacter springFontCharacter77 = new SpringFontCharacter('れ', new Rectangle(171, 77, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter77.Character, springFontCharacter77);
      SpringFontCharacter springFontCharacter78 = new SpringFontCharacter('ろ', new Rectangle(188, 77, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter78.Character, springFontCharacter78);
      SpringFontCharacter springFontCharacter79 = new SpringFontCharacter('ゎ', new Rectangle(201, 77, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter79.Character, springFontCharacter79);
      SpringFontCharacter springFontCharacter80 = new SpringFontCharacter('わ', new Rectangle(213, 77, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter80.Character, springFontCharacter80);
      SpringFontCharacter springFontCharacter81 = new SpringFontCharacter('ゐ', new Rectangle(1, 96, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter81.Character, springFontCharacter81);
      SpringFontCharacter springFontCharacter82 = new SpringFontCharacter('ゑ', new Rectangle(18, 96, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter82.Character, springFontCharacter82);
      SpringFontCharacter springFontCharacter83 = new SpringFontCharacter('を', new Rectangle(35, 96, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter83.Character, springFontCharacter83);
      SpringFontCharacter springFontCharacter84 = new SpringFontCharacter('ん', new Rectangle(50, 96, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter84.Character, springFontCharacter84);
      SpringFontCharacter springFontCharacter85 = new SpringFontCharacter('ゔ', new Rectangle(67, 96, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter85.Character, springFontCharacter85);
      SpringFontCharacter springFontCharacter86 = new SpringFontCharacter('ゕ', new Rectangle(82, 96, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter86.Character, springFontCharacter86);
      SpringFontCharacter springFontCharacter87 = new SpringFontCharacter('ゖ', new Rectangle(95, 96, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter87.Character, springFontCharacter87);
      SpringFontCharacter springFontCharacter88 = new SpringFontCharacter('\u3097', new Rectangle(108, 96, 7, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter88.Character, springFontCharacter88);
      SpringFontCharacter springFontCharacter89 = new SpringFontCharacter('\u3098', new Rectangle(116, 96, 7, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter89.Character, springFontCharacter89);
      SpringFontCharacter springFontCharacter90 = new SpringFontCharacter('゙', new Rectangle(124, 96, 13, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter90.Character, springFontCharacter90);
      SpringFontCharacter springFontCharacter91 = new SpringFontCharacter('゚', new Rectangle(138, 96, 13, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter91.Character, springFontCharacter91);
      SpringFontCharacter springFontCharacter92 = new SpringFontCharacter('゛', new Rectangle(152, 96, 8, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter92.Character, springFontCharacter92);
      SpringFontCharacter springFontCharacter93 = new SpringFontCharacter('゜', new Rectangle(161, 96, 8, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter93.Character, springFontCharacter93);
      SpringFontCharacter springFontCharacter94 = new SpringFontCharacter('ゝ', new Rectangle(170, 96, 8, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter94.Character, springFontCharacter94);
      SpringFontCharacter springFontCharacter95 = new SpringFontCharacter('ゞ', new Rectangle(179, 96, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter95.Character, springFontCharacter95);
      SpringFontCharacter springFontCharacter96 = new SpringFontCharacter('ゟ', new Rectangle(191, 96, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter96.Character, springFontCharacter96);
      SpringFontCharacter springFontCharacter97 = new SpringFontCharacter('゠', new Rectangle(1, 115, 9, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter97.Character, springFontCharacter97);
      SpringFontCharacter springFontCharacter98 = new SpringFontCharacter('ァ', new Rectangle(11, 115, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter98.Character, springFontCharacter98);
      SpringFontCharacter springFontCharacter99 = new SpringFontCharacter('ア', new Rectangle(23, 115, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter99.Character, springFontCharacter99);
      SpringFontCharacter springFontCharacter100 = new SpringFontCharacter('ィ', new Rectangle(40, 115, 10, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter100.Character, springFontCharacter100);
      SpringFontCharacter springFontCharacter101 = new SpringFontCharacter('イ', new Rectangle(51, 115, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter101.Character, springFontCharacter101);
      SpringFontCharacter springFontCharacter102 = new SpringFontCharacter('ゥ', new Rectangle(66, 115, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter102.Character, springFontCharacter102);
      SpringFontCharacter springFontCharacter103 = new SpringFontCharacter('ウ', new Rectangle(78, 115, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter103.Character, springFontCharacter103);
      SpringFontCharacter springFontCharacter104 = new SpringFontCharacter('ェ', new Rectangle(93, 115, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter104.Character, springFontCharacter104);
      SpringFontCharacter springFontCharacter105 = new SpringFontCharacter('エ', new Rectangle(105, 115, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter105.Character, springFontCharacter105);
      SpringFontCharacter springFontCharacter106 = new SpringFontCharacter('ォ', new Rectangle(123, 115, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter106.Character, springFontCharacter106);
      SpringFontCharacter springFontCharacter107 = new SpringFontCharacter('オ', new Rectangle(135, 115, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter107.Character, springFontCharacter107);
      SpringFontCharacter springFontCharacter108 = new SpringFontCharacter('カ', new Rectangle(152, 115, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter108.Character, springFontCharacter108);
      SpringFontCharacter springFontCharacter109 = new SpringFontCharacter('ガ', new Rectangle(169, 115, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter109.Character, springFontCharacter109);
      SpringFontCharacter springFontCharacter110 = new SpringFontCharacter('キ', new Rectangle(187, 115, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter110.Character, springFontCharacter110);
      SpringFontCharacter springFontCharacter111 = new SpringFontCharacter('ギ', new Rectangle(204, 115, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter111.Character, springFontCharacter111);
      SpringFontCharacter springFontCharacter112 = new SpringFontCharacter('ク', new Rectangle(222, 115, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter112.Character, springFontCharacter112);
      SpringFontCharacter springFontCharacter113 = new SpringFontCharacter('グ', new Rectangle(1, 134, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter113.Character, springFontCharacter113);
      SpringFontCharacter springFontCharacter114 = new SpringFontCharacter('ケ', new Rectangle(18, 134, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter114.Character, springFontCharacter114);
      SpringFontCharacter springFontCharacter115 = new SpringFontCharacter('ゲ', new Rectangle(35, 134, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter115.Character, springFontCharacter115);
      SpringFontCharacter springFontCharacter116 = new SpringFontCharacter('コ', new Rectangle(53, 134, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter116.Character, springFontCharacter116);
      SpringFontCharacter springFontCharacter117 = new SpringFontCharacter('ゴ', new Rectangle(68, 134, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter117.Character, springFontCharacter117);
      SpringFontCharacter springFontCharacter118 = new SpringFontCharacter('サ', new Rectangle(85, 134, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter118.Character, springFontCharacter118);
      SpringFontCharacter springFontCharacter119 = new SpringFontCharacter('ザ', new Rectangle(102, 134, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter119.Character, springFontCharacter119);
      SpringFontCharacter springFontCharacter120 = new SpringFontCharacter('シ', new Rectangle(120, 134, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter120.Character, springFontCharacter120);
      SpringFontCharacter springFontCharacter121 = new SpringFontCharacter('ジ', new Rectangle(137, 134, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter121.Character, springFontCharacter121);
      SpringFontCharacter springFontCharacter122 = new SpringFontCharacter('ス', new Rectangle(154, 134, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter122.Character, springFontCharacter122);
      SpringFontCharacter springFontCharacter123 = new SpringFontCharacter('ズ', new Rectangle(171, 134, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter123.Character, springFontCharacter123);
      SpringFontCharacter springFontCharacter124 = new SpringFontCharacter('セ', new Rectangle(189, 134, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter124.Character, springFontCharacter124);
      SpringFontCharacter springFontCharacter125 = new SpringFontCharacter('ゼ', new Rectangle(207, 134, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter125.Character, springFontCharacter125);
      SpringFontCharacter springFontCharacter126 = new SpringFontCharacter('ソ', new Rectangle(225, 134, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter126.Character, springFontCharacter126);
      SpringFontCharacter springFontCharacter127 = new SpringFontCharacter('ゾ', new Rectangle(240, 134, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter127.Character, springFontCharacter127);
      SpringFontCharacter springFontCharacter128 = new SpringFontCharacter('タ', new Rectangle(258, 134, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter128.Character, springFontCharacter128);
      SpringFontCharacter springFontCharacter129 = new SpringFontCharacter('ダ', new Rectangle(1, 153, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter129.Character, springFontCharacter129);
      SpringFontCharacter springFontCharacter130 = new SpringFontCharacter('チ', new Rectangle(18, 153, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter130.Character, springFontCharacter130);
      SpringFontCharacter springFontCharacter131 = new SpringFontCharacter('ヂ', new Rectangle(36, 153, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter131.Character, springFontCharacter131);
      SpringFontCharacter springFontCharacter132 = new SpringFontCharacter('ッ', new Rectangle(54, 153, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter132.Character, springFontCharacter132);
      SpringFontCharacter springFontCharacter133 = new SpringFontCharacter('ツ', new Rectangle(66, 153, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter133.Character, springFontCharacter133);
      SpringFontCharacter springFontCharacter134 = new SpringFontCharacter('ヅ', new Rectangle(81, 153, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter134.Character, springFontCharacter134);
      SpringFontCharacter springFontCharacter135 = new SpringFontCharacter('テ', new Rectangle(99, 153, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter135.Character, springFontCharacter135);
      SpringFontCharacter springFontCharacter136 = new SpringFontCharacter('デ', new Rectangle(116, 153, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter136.Character, springFontCharacter136);
      SpringFontCharacter springFontCharacter137 = new SpringFontCharacter('ト', new Rectangle(134, 153, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter137.Character, springFontCharacter137);
      SpringFontCharacter springFontCharacter138 = new SpringFontCharacter('ド', new Rectangle(146, 153, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter138.Character, springFontCharacter138);
      SpringFontCharacter springFontCharacter139 = new SpringFontCharacter('ナ', new Rectangle(159, 153, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter139.Character, springFontCharacter139);
      SpringFontCharacter springFontCharacter140 = new SpringFontCharacter('ニ', new Rectangle(176, 153, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter140.Character, springFontCharacter140);
      SpringFontCharacter springFontCharacter141 = new SpringFontCharacter('ヌ', new Rectangle(193, 153, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter141.Character, springFontCharacter141);
      SpringFontCharacter springFontCharacter142 = new SpringFontCharacter('ネ', new Rectangle(208, 153, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter142.Character, springFontCharacter142);
      SpringFontCharacter springFontCharacter143 = new SpringFontCharacter('ノ', new Rectangle(226, 153, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter143.Character, springFontCharacter143);
      SpringFontCharacter springFontCharacter144 = new SpringFontCharacter('ハ', new Rectangle(238, 153, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter144.Character, springFontCharacter144);
      SpringFontCharacter springFontCharacter145 = new SpringFontCharacter('バ', new Rectangle(1, 172, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter145.Character, springFontCharacter145);
      SpringFontCharacter springFontCharacter146 = new SpringFontCharacter('パ', new Rectangle(18, 172, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter146.Character, springFontCharacter146);
      SpringFontCharacter springFontCharacter147 = new SpringFontCharacter('ヒ', new Rectangle(35, 172, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter147.Character, springFontCharacter147);
      SpringFontCharacter springFontCharacter148 = new SpringFontCharacter('ビ', new Rectangle(48, 172, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter148.Character, springFontCharacter148);
      SpringFontCharacter springFontCharacter149 = new SpringFontCharacter('ピ', new Rectangle(63, 172, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter149.Character, springFontCharacter149);
      SpringFontCharacter springFontCharacter150 = new SpringFontCharacter('フ', new Rectangle(80, 172, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter150.Character, springFontCharacter150);
      SpringFontCharacter springFontCharacter151 = new SpringFontCharacter('ブ', new Rectangle(95, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter151.Character, springFontCharacter151);
      SpringFontCharacter springFontCharacter152 = new SpringFontCharacter('プ', new Rectangle(113, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter152.Character, springFontCharacter152);
      SpringFontCharacter springFontCharacter153 = new SpringFontCharacter('ヘ', new Rectangle(131, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter153.Character, springFontCharacter153);
      SpringFontCharacter springFontCharacter154 = new SpringFontCharacter('ベ', new Rectangle(149, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter154.Character, springFontCharacter154);
      SpringFontCharacter springFontCharacter155 = new SpringFontCharacter('ペ', new Rectangle(167, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter155.Character, springFontCharacter155);
      SpringFontCharacter springFontCharacter156 = new SpringFontCharacter('ホ', new Rectangle(185, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter156.Character, springFontCharacter156);
      SpringFontCharacter springFontCharacter157 = new SpringFontCharacter('ボ', new Rectangle(203, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter157.Character, springFontCharacter157);
      SpringFontCharacter springFontCharacter158 = new SpringFontCharacter('ポ', new Rectangle(221, 172, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter158.Character, springFontCharacter158);
      SpringFontCharacter springFontCharacter159 = new SpringFontCharacter('マ', new Rectangle(239, 172, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter159.Character, springFontCharacter159);
      SpringFontCharacter springFontCharacter160 = new SpringFontCharacter('ミ', new Rectangle(256, 172, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter160.Character, springFontCharacter160);
      SpringFontCharacter springFontCharacter161 = new SpringFontCharacter('ム', new Rectangle(1, 191, 15, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter161.Character, springFontCharacter161);
      SpringFontCharacter springFontCharacter162 = new SpringFontCharacter('メ', new Rectangle(17, 191, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter162.Character, springFontCharacter162);
      SpringFontCharacter springFontCharacter163 = new SpringFontCharacter('モ', new Rectangle(34, 191, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter163.Character, springFontCharacter163);
      SpringFontCharacter springFontCharacter164 = new SpringFontCharacter('ャ', new Rectangle(52, 191, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter164.Character, springFontCharacter164);
      SpringFontCharacter springFontCharacter165 = new SpringFontCharacter('ヤ', new Rectangle(64, 191, 15, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter165.Character, springFontCharacter165);
      SpringFontCharacter springFontCharacter166 = new SpringFontCharacter('ュ', new Rectangle(80, 191, 13, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter166.Character, springFontCharacter166);
      SpringFontCharacter springFontCharacter167 = new SpringFontCharacter('ユ', new Rectangle(94, 191, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter167.Character, springFontCharacter167);
      SpringFontCharacter springFontCharacter168 = new SpringFontCharacter('ョ', new Rectangle(112, 191, 10, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter168.Character, springFontCharacter168);
      SpringFontCharacter springFontCharacter169 = new SpringFontCharacter('ヨ', new Rectangle(123, 191, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter169.Character, springFontCharacter169);
      SpringFontCharacter springFontCharacter170 = new SpringFontCharacter('ラ', new Rectangle(136, 191, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter170.Character, springFontCharacter170);
      SpringFontCharacter springFontCharacter171 = new SpringFontCharacter('リ', new Rectangle(151, 191, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter171.Character, springFontCharacter171);
      SpringFontCharacter springFontCharacter172 = new SpringFontCharacter('ル', new Rectangle(163, 191, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter172.Character, springFontCharacter172);
      SpringFontCharacter springFontCharacter173 = new SpringFontCharacter('レ', new Rectangle(180, 191, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter173.Character, springFontCharacter173);
      SpringFontCharacter springFontCharacter174 = new SpringFontCharacter('ロ', new Rectangle(193, 191, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter174.Character, springFontCharacter174);
      SpringFontCharacter springFontCharacter175 = new SpringFontCharacter('ヮ', new Rectangle(208, 191, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter175.Character, springFontCharacter175);
      SpringFontCharacter springFontCharacter176 = new SpringFontCharacter('ワ', new Rectangle(220, 191, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter176.Character, springFontCharacter176);
      SpringFontCharacter springFontCharacter177 = new SpringFontCharacter('ヰ', new Rectangle(1, 210, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter177.Character, springFontCharacter177);
      SpringFontCharacter springFontCharacter178 = new SpringFontCharacter('ヱ', new Rectangle(18, 210, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter178.Character, springFontCharacter178);
      SpringFontCharacter springFontCharacter179 = new SpringFontCharacter('ヲ', new Rectangle(35, 210, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter179.Character, springFontCharacter179);
      SpringFontCharacter springFontCharacter180 = new SpringFontCharacter('ン', new Rectangle(48, 210, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter180.Character, springFontCharacter180);
      SpringFontCharacter springFontCharacter181 = new SpringFontCharacter('ヴ', new Rectangle(63, 210, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter181.Character, springFontCharacter181);
      SpringFontCharacter springFontCharacter182 = new SpringFontCharacter('ヵ', new Rectangle(80, 210, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter182.Character, springFontCharacter182);
      SpringFontCharacter springFontCharacter183 = new SpringFontCharacter('ヶ', new Rectangle(92, 210, 11, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter183.Character, springFontCharacter183);
      SpringFontCharacter springFontCharacter184 = new SpringFontCharacter('ヷ', new Rectangle(104, 210, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter184.Character, springFontCharacter184);
      SpringFontCharacter springFontCharacter185 = new SpringFontCharacter('ヸ', new Rectangle(122, 210, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter185.Character, springFontCharacter185);
      SpringFontCharacter springFontCharacter186 = new SpringFontCharacter('ヹ', new Rectangle(140, 210, 17, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter186.Character, springFontCharacter186);
      SpringFontCharacter springFontCharacter187 = new SpringFontCharacter('ヺ', new Rectangle(158, 210, 16, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter187.Character, springFontCharacter187);
      SpringFontCharacter springFontCharacter188 = new SpringFontCharacter('・', new Rectangle(175, 210, 5, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter188.Character, springFontCharacter188);
      SpringFontCharacter springFontCharacter189 = new SpringFontCharacter('ー', new Rectangle(181, 210, 14, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter189.Character, springFontCharacter189);
      SpringFontCharacter springFontCharacter190 = new SpringFontCharacter('ヽ', new Rectangle(196, 210, 7, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter190.Character, springFontCharacter190);
      SpringFontCharacter springFontCharacter191 = new SpringFontCharacter('ヾ', new Rectangle(204, 210, 12, 18), 0.44f, _RightSpacing: -0.55f);
      FontDictionary.Add(springFontCharacter191.Character, springFontCharacter191);
    }

    public FontSet_Hiragana_Hiragana()
    {
      this.CharacterSet = CharSet.Hiragana;
      this.TextureFileName = "hiragana";
      this.startIndex = 12352;
      this.endIndex = 12542;
    }
  }
}
