// Decompiled with JetBrains decompiler
// Type: TinyZoo.FontSet_BiggerPixel_English
// Assembly: LetsBuildAZoo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DEB7467C-E857-4369-A6B7-78A1E0037E5E
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Let's Build a Zoo Demo\LetsBuildAZoo.exe

using Microsoft.Xna.Framework;
using SEngine;
using System.Collections.Generic;

namespace TinyZoo
{
  internal class FontSet_BiggerPixel_English : FontBase
  {
    public override void CreateFontSet(
      Dictionary<char, SpringFontCharacter> FontDictionary)
    {
      SpringFontCharacter springFontCharacter1 = new SpringFontCharacter(' ', new Rectangle(1, 1, 3, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter1.Character, springFontCharacter1);
      SpringFontCharacter springFontCharacter2 = new SpringFontCharacter('!', new Rectangle(5, 1, 3, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter2.Character, springFontCharacter2);
      SpringFontCharacter springFontCharacter3 = new SpringFontCharacter('"', new Rectangle(9, 1, 6, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter3.Character, springFontCharacter3);
      SpringFontCharacter springFontCharacter4 = new SpringFontCharacter('#', new Rectangle(16, 1, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter4.Character, springFontCharacter4);
      SpringFontCharacter springFontCharacter5 = new SpringFontCharacter('$', new Rectangle(26, 1, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter5.Character, springFontCharacter5);
      SpringFontCharacter springFontCharacter6 = new SpringFontCharacter('%', new Rectangle(36, 1, 10, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter6.Character, springFontCharacter6);
      SpringFontCharacter springFontCharacter7 = new SpringFontCharacter('&', new Rectangle(47, 1, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter7.Character, springFontCharacter7);
      SpringFontCharacter springFontCharacter8 = new SpringFontCharacter('\'', new Rectangle(57, 1, 4, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter8.Character, springFontCharacter8);
      SpringFontCharacter springFontCharacter9 = new SpringFontCharacter('(', new Rectangle(62, 1, 5, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter9.Character, springFontCharacter9);
      SpringFontCharacter springFontCharacter10 = new SpringFontCharacter(')', new Rectangle(68, 1, 6, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter10.Character, springFontCharacter10);
      SpringFontCharacter springFontCharacter11 = new SpringFontCharacter('*', new Rectangle(75, 1, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter11.Character, springFontCharacter11);
      SpringFontCharacter springFontCharacter12 = new SpringFontCharacter('+', new Rectangle(83, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter12.Character, springFontCharacter12);
      SpringFontCharacter springFontCharacter13 = new SpringFontCharacter(',', new Rectangle(92, 1, 4, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter13.Character, springFontCharacter13);
      SpringFontCharacter springFontCharacter14 = new SpringFontCharacter('-', new Rectangle(97, 1, 6, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter14.Character, springFontCharacter14);
      SpringFontCharacter springFontCharacter15 = new SpringFontCharacter('.', new Rectangle(104, 1, 4, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter15.Character, springFontCharacter15);
      SpringFontCharacter springFontCharacter16 = new SpringFontCharacter('/', new Rectangle(109, 1, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter16.Character, springFontCharacter16);
      SpringFontCharacter springFontCharacter17 = new SpringFontCharacter('0', new Rectangle(117, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter17.Character, springFontCharacter17);
      SpringFontCharacter springFontCharacter18 = new SpringFontCharacter('1', new Rectangle(126, 1, 5, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter18.Character, springFontCharacter18);
      SpringFontCharacter springFontCharacter19 = new SpringFontCharacter('2', new Rectangle(132, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter19.Character, springFontCharacter19);
      SpringFontCharacter springFontCharacter20 = new SpringFontCharacter('3', new Rectangle(141, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter20.Character, springFontCharacter20);
      SpringFontCharacter springFontCharacter21 = new SpringFontCharacter('4', new Rectangle(150, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter21.Character, springFontCharacter21);
      SpringFontCharacter springFontCharacter22 = new SpringFontCharacter('5', new Rectangle(159, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter22.Character, springFontCharacter22);
      SpringFontCharacter springFontCharacter23 = new SpringFontCharacter('6', new Rectangle(168, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter23.Character, springFontCharacter23);
      SpringFontCharacter springFontCharacter24 = new SpringFontCharacter('7', new Rectangle(177, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter24.Character, springFontCharacter24);
      SpringFontCharacter springFontCharacter25 = new SpringFontCharacter('8', new Rectangle(186, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter25.Character, springFontCharacter25);
      SpringFontCharacter springFontCharacter26 = new SpringFontCharacter('9', new Rectangle(195, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter26.Character, springFontCharacter26);
      SpringFontCharacter springFontCharacter27 = new SpringFontCharacter(':', new Rectangle(204, 1, 4, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter27.Character, springFontCharacter27);
      SpringFontCharacter springFontCharacter28 = new SpringFontCharacter(';', new Rectangle(209, 1, 4, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter28.Character, springFontCharacter28);
      SpringFontCharacter springFontCharacter29 = new SpringFontCharacter('<', new Rectangle(214, 1, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter29.Character, springFontCharacter29);
      SpringFontCharacter springFontCharacter30 = new SpringFontCharacter('=', new Rectangle(222, 1, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter30.Character, springFontCharacter30);
      SpringFontCharacter springFontCharacter31 = new SpringFontCharacter('>', new Rectangle(230, 1, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter31.Character, springFontCharacter31);
      SpringFontCharacter springFontCharacter32 = new SpringFontCharacter('?', new Rectangle(238, 1, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter32.Character, springFontCharacter32);
      SpringFontCharacter springFontCharacter33 = new SpringFontCharacter('@', new Rectangle(1, 16, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter33.Character, springFontCharacter33);
      SpringFontCharacter springFontCharacter34 = new SpringFontCharacter('A', new Rectangle(11, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter34.Character, springFontCharacter34);
      SpringFontCharacter springFontCharacter35 = new SpringFontCharacter('B', new Rectangle(20, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter35.Character, springFontCharacter35);
      SpringFontCharacter springFontCharacter36 = new SpringFontCharacter('C', new Rectangle(29, 16, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter36.Character, springFontCharacter36);
      SpringFontCharacter springFontCharacter37 = new SpringFontCharacter('D', new Rectangle(37, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter37.Character, springFontCharacter37);
      SpringFontCharacter springFontCharacter38 = new SpringFontCharacter('E', new Rectangle(46, 16, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter38.Character, springFontCharacter38);
      SpringFontCharacter springFontCharacter39 = new SpringFontCharacter('F', new Rectangle(54, 16, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter39.Character, springFontCharacter39);
      SpringFontCharacter springFontCharacter40 = new SpringFontCharacter('G', new Rectangle(62, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter40.Character, springFontCharacter40);
      SpringFontCharacter springFontCharacter41 = new SpringFontCharacter('H', new Rectangle(71, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter41.Character, springFontCharacter41);
      SpringFontCharacter springFontCharacter42 = new SpringFontCharacter('I', new Rectangle(80, 16, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter42.Character, springFontCharacter42);
      SpringFontCharacter springFontCharacter43 = new SpringFontCharacter('J', new Rectangle(88, 16, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter43.Character, springFontCharacter43);
      SpringFontCharacter springFontCharacter44 = new SpringFontCharacter('K', new Rectangle(98, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter44.Character, springFontCharacter44);
      SpringFontCharacter springFontCharacter45 = new SpringFontCharacter('L', new Rectangle(107, 16, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter45.Character, springFontCharacter45);
      SpringFontCharacter springFontCharacter46 = new SpringFontCharacter('M', new Rectangle(115, 16, 10, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter46.Character, springFontCharacter46);
      SpringFontCharacter springFontCharacter47 = new SpringFontCharacter('N', new Rectangle(126, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter47.Character, springFontCharacter47);
      SpringFontCharacter springFontCharacter48 = new SpringFontCharacter('O', new Rectangle(135, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter48.Character, springFontCharacter48);
      SpringFontCharacter springFontCharacter49 = new SpringFontCharacter('P', new Rectangle(144, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter49.Character, springFontCharacter49);
      SpringFontCharacter springFontCharacter50 = new SpringFontCharacter('Q', new Rectangle(153, 16, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter50.Character, springFontCharacter50);
      SpringFontCharacter springFontCharacter51 = new SpringFontCharacter('R', new Rectangle(163, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter51.Character, springFontCharacter51);
      SpringFontCharacter springFontCharacter52 = new SpringFontCharacter('S', new Rectangle(172, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter52.Character, springFontCharacter52);
      SpringFontCharacter springFontCharacter53 = new SpringFontCharacter('T', new Rectangle(181, 16, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter53.Character, springFontCharacter53);
      SpringFontCharacter springFontCharacter54 = new SpringFontCharacter('U', new Rectangle(189, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter54.Character, springFontCharacter54);
      SpringFontCharacter springFontCharacter55 = new SpringFontCharacter('V', new Rectangle(198, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter55.Character, springFontCharacter55);
      SpringFontCharacter springFontCharacter56 = new SpringFontCharacter('W', new Rectangle(207, 16, 10, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter56.Character, springFontCharacter56);
      SpringFontCharacter springFontCharacter57 = new SpringFontCharacter('X', new Rectangle(218, 16, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter57.Character, springFontCharacter57);
      SpringFontCharacter springFontCharacter58 = new SpringFontCharacter('Y', new Rectangle(228, 16, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter58.Character, springFontCharacter58);
      SpringFontCharacter springFontCharacter59 = new SpringFontCharacter('Z', new Rectangle(237, 16, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter59.Character, springFontCharacter59);
      SpringFontCharacter springFontCharacter60 = new SpringFontCharacter('[', new Rectangle(1, 31, 5, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter60.Character, springFontCharacter60);
      SpringFontCharacter springFontCharacter61 = new SpringFontCharacter('\\', new Rectangle(7, 31, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter61.Character, springFontCharacter61);
      SpringFontCharacter springFontCharacter62 = new SpringFontCharacter(']', new Rectangle(15, 31, 6, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter62.Character, springFontCharacter62);
      SpringFontCharacter springFontCharacter63 = new SpringFontCharacter('^', new Rectangle(22, 31, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter63.Character, springFontCharacter63);
      SpringFontCharacter springFontCharacter64 = new SpringFontCharacter('_', new Rectangle(30, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter64.Character, springFontCharacter64);
      SpringFontCharacter springFontCharacter65 = new SpringFontCharacter('`', new Rectangle(39, 31, 5, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter65.Character, springFontCharacter65);
      SpringFontCharacter springFontCharacter66 = new SpringFontCharacter('a', new Rectangle(45, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter66.Character, springFontCharacter66);
      SpringFontCharacter springFontCharacter67 = new SpringFontCharacter('b', new Rectangle(54, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter67.Character, springFontCharacter67);
      SpringFontCharacter springFontCharacter68 = new SpringFontCharacter('c', new Rectangle(63, 31, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter68.Character, springFontCharacter68);
      SpringFontCharacter springFontCharacter69 = new SpringFontCharacter('d', new Rectangle(71, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter69.Character, springFontCharacter69);
      SpringFontCharacter springFontCharacter70 = new SpringFontCharacter('e', new Rectangle(80, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter70.Character, springFontCharacter70);
      SpringFontCharacter springFontCharacter71 = new SpringFontCharacter('f', new Rectangle(89, 31, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter71.Character, springFontCharacter71);
      SpringFontCharacter springFontCharacter72 = new SpringFontCharacter('g', new Rectangle(97, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter72.Character, springFontCharacter72);
      SpringFontCharacter springFontCharacter73 = new SpringFontCharacter('h', new Rectangle(106, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter73.Character, springFontCharacter73);
      SpringFontCharacter springFontCharacter74 = new SpringFontCharacter('i', new Rectangle(115, 31, 3, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter74.Character, springFontCharacter74);
      SpringFontCharacter springFontCharacter75 = new SpringFontCharacter('j', new Rectangle(119, 31, 6, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter75.Character, springFontCharacter75);
      SpringFontCharacter springFontCharacter76 = new SpringFontCharacter('k', new Rectangle(126, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter76.Character, springFontCharacter76);
      SpringFontCharacter springFontCharacter77 = new SpringFontCharacter('l', new Rectangle(135, 31, 3, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter77.Character, springFontCharacter77);
      SpringFontCharacter springFontCharacter78 = new SpringFontCharacter('m', new Rectangle(139, 31, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter78.Character, springFontCharacter78);
      SpringFontCharacter springFontCharacter79 = new SpringFontCharacter('n', new Rectangle(149, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter79.Character, springFontCharacter79);
      SpringFontCharacter springFontCharacter80 = new SpringFontCharacter('o', new Rectangle(158, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter80.Character, springFontCharacter80);
      SpringFontCharacter springFontCharacter81 = new SpringFontCharacter('p', new Rectangle(167, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter81.Character, springFontCharacter81);
      SpringFontCharacter springFontCharacter82 = new SpringFontCharacter('q', new Rectangle(176, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter82.Character, springFontCharacter82);
      SpringFontCharacter springFontCharacter83 = new SpringFontCharacter('r', new Rectangle(185, 31, 6, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter83.Character, springFontCharacter83);
      SpringFontCharacter springFontCharacter84 = new SpringFontCharacter('s', new Rectangle(192, 31, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter84.Character, springFontCharacter84);
      SpringFontCharacter springFontCharacter85 = new SpringFontCharacter('t', new Rectangle(200, 31, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter85.Character, springFontCharacter85);
      SpringFontCharacter springFontCharacter86 = new SpringFontCharacter('u', new Rectangle(208, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter86.Character, springFontCharacter86);
      SpringFontCharacter springFontCharacter87 = new SpringFontCharacter('v', new Rectangle(217, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter87.Character, springFontCharacter87);
      SpringFontCharacter springFontCharacter88 = new SpringFontCharacter('w', new Rectangle(226, 31, 10, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter88.Character, springFontCharacter88);
      SpringFontCharacter springFontCharacter89 = new SpringFontCharacter('x', new Rectangle(237, 31, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter89.Character, springFontCharacter89);
      SpringFontCharacter springFontCharacter90 = new SpringFontCharacter('y', new Rectangle(1, 46, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter90.Character, springFontCharacter90);
      SpringFontCharacter springFontCharacter91 = new SpringFontCharacter('z', new Rectangle(10, 46, 8, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter91.Character, springFontCharacter91);
      SpringFontCharacter springFontCharacter92 = new SpringFontCharacter('{', new Rectangle(19, 46, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter92.Character, springFontCharacter92);
      SpringFontCharacter springFontCharacter93 = new SpringFontCharacter('|', new Rectangle(27, 46, 3, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter93.Character, springFontCharacter93);
      SpringFontCharacter springFontCharacter94 = new SpringFontCharacter('}', new Rectangle(31, 46, 7, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter94.Character, springFontCharacter94);
      SpringFontCharacter springFontCharacter95 = new SpringFontCharacter('~', new Rectangle(39, 46, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter95.Character, springFontCharacter95);
      SpringFontCharacter springFontCharacter96 = new SpringFontCharacter('\u007F', new Rectangle(49, 46, 5, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter96.Character, springFontCharacter96);
      SpringFontCharacter springFontCharacter97 = new SpringFontCharacter(' ', new Rectangle(55, 46, 5, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter97.Character, springFontCharacter97);
      SpringFontCharacter springFontCharacter98 = new SpringFontCharacter('¡', new Rectangle(61, 46, 3, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter98.Character, springFontCharacter98);
      SpringFontCharacter springFontCharacter99 = new SpringFontCharacter('¢', new Rectangle(65, 46, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter99.Character, springFontCharacter99);
      SpringFontCharacter springFontCharacter100 = new SpringFontCharacter('£', new Rectangle(75, 46, 10, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter100.Character, springFontCharacter100);
      SpringFontCharacter springFontCharacter101 = new SpringFontCharacter('¤', new Rectangle(86, 46, 9, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter101.Character, springFontCharacter101);
      SpringFontCharacter springFontCharacter102 = new SpringFontCharacter('¥', new Rectangle(96, 46, 10, 14), 1f, _RightSpacing: 0.5f);
      FontDictionary.Add(springFontCharacter102.Character, springFontCharacter102);
    }

    public FontSet_BiggerPixel_English()
    {
      this.CharacterSet = CharSet.English;
      this.TextureFileName = "Fonts/RevisedPixelFontX1.5_SpringFont";
      this.startIndex = 32;
      this.endIndex = 165;
    }
  }
}
