// Decompiled with JetBrains decompiler
// Type: TinyZoo.FontSet_JapaneseRoman_CJK
// Assembly: LetsBuildAZoo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DEB7467C-E857-4369-A6B7-78A1E0037E5E
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Let's Build a Zoo Demo\LetsBuildAZoo.exe

using Microsoft.Xna.Framework;
using SEngine;
using System.Collections.Generic;

namespace TinyZoo
{
  internal class FontSet_JapaneseRoman_CJK : FontBase
  {
    public override void CreateFontSet(
      Dictionary<char, SpringFontCharacter> FontDictionary)
    {
      SpringFontCharacter springFontCharacter1 = new SpringFontCharacter('\uFF00', new Rectangle(1, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter1.Character, springFontCharacter1);
      SpringFontCharacter springFontCharacter2 = new SpringFontCharacter('！', new Rectangle(8, 1, 14, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter2.Character, springFontCharacter2);
      SpringFontCharacter springFontCharacter3 = new SpringFontCharacter('＂', new Rectangle(23, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter3.Character, springFontCharacter3);
      SpringFontCharacter springFontCharacter4 = new SpringFontCharacter('＃', new Rectangle(30, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter4.Character, springFontCharacter4);
      SpringFontCharacter springFontCharacter5 = new SpringFontCharacter('＄', new Rectangle(40, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter5.Character, springFontCharacter5);
      SpringFontCharacter springFontCharacter6 = new SpringFontCharacter('％', new Rectangle(50, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter6.Character, springFontCharacter6);
      SpringFontCharacter springFontCharacter7 = new SpringFontCharacter('＆', new Rectangle(60, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter7.Character, springFontCharacter7);
      SpringFontCharacter springFontCharacter8 = new SpringFontCharacter('＇', new Rectangle(70, 1, 14, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter8.Character, springFontCharacter8);
      SpringFontCharacter springFontCharacter9 = new SpringFontCharacter('（', new Rectangle(85, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter9.Character, springFontCharacter9);
      SpringFontCharacter springFontCharacter10 = new SpringFontCharacter('）', new Rectangle(92, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter10.Character, springFontCharacter10);
      SpringFontCharacter springFontCharacter11 = new SpringFontCharacter('＊', new Rectangle(99, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter11.Character, springFontCharacter11);
      SpringFontCharacter springFontCharacter12 = new SpringFontCharacter('＋', new Rectangle(109, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter12.Character, springFontCharacter12);
      SpringFontCharacter springFontCharacter13 = new SpringFontCharacter('，', new Rectangle(119, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter13.Character, springFontCharacter13);
      SpringFontCharacter springFontCharacter14 = new SpringFontCharacter('－', new Rectangle(126, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter14.Character, springFontCharacter14);
      SpringFontCharacter springFontCharacter15 = new SpringFontCharacter('．', new Rectangle(136, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter15.Character, springFontCharacter15);
      SpringFontCharacter springFontCharacter16 = new SpringFontCharacter('／', new Rectangle(143, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter16.Character, springFontCharacter16);
      SpringFontCharacter springFontCharacter17 = new SpringFontCharacter('０', new Rectangle(153, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter17.Character, springFontCharacter17);
      SpringFontCharacter springFontCharacter18 = new SpringFontCharacter('１', new Rectangle(163, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter18.Character, springFontCharacter18);
      SpringFontCharacter springFontCharacter19 = new SpringFontCharacter('２', new Rectangle(170, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter19.Character, springFontCharacter19);
      SpringFontCharacter springFontCharacter20 = new SpringFontCharacter('３', new Rectangle(180, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter20.Character, springFontCharacter20);
      SpringFontCharacter springFontCharacter21 = new SpringFontCharacter('４', new Rectangle(190, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter21.Character, springFontCharacter21);
      SpringFontCharacter springFontCharacter22 = new SpringFontCharacter('５', new Rectangle(200, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter22.Character, springFontCharacter22);
      SpringFontCharacter springFontCharacter23 = new SpringFontCharacter('６', new Rectangle(210, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter23.Character, springFontCharacter23);
      SpringFontCharacter springFontCharacter24 = new SpringFontCharacter('７', new Rectangle(220, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter24.Character, springFontCharacter24);
      SpringFontCharacter springFontCharacter25 = new SpringFontCharacter('８', new Rectangle(230, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter25.Character, springFontCharacter25);
      SpringFontCharacter springFontCharacter26 = new SpringFontCharacter('９', new Rectangle(240, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter26.Character, springFontCharacter26);
      SpringFontCharacter springFontCharacter27 = new SpringFontCharacter('：', new Rectangle(250, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter27.Character, springFontCharacter27);
      SpringFontCharacter springFontCharacter28 = new SpringFontCharacter('；', new Rectangle(257, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter28.Character, springFontCharacter28);
      SpringFontCharacter springFontCharacter29 = new SpringFontCharacter('＜', new Rectangle(264, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter29.Character, springFontCharacter29);
      SpringFontCharacter springFontCharacter30 = new SpringFontCharacter('＝', new Rectangle(274, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter30.Character, springFontCharacter30);
      SpringFontCharacter springFontCharacter31 = new SpringFontCharacter('＞', new Rectangle(284, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter31.Character, springFontCharacter31);
      SpringFontCharacter springFontCharacter32 = new SpringFontCharacter('？', new Rectangle(294, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter32.Character, springFontCharacter32);
      SpringFontCharacter springFontCharacter33 = new SpringFontCharacter('＠', new Rectangle(304, 1, 10, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter33.Character, springFontCharacter33);
      SpringFontCharacter springFontCharacter34 = new SpringFontCharacter('Ａ', new Rectangle(315, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter34.Character, springFontCharacter34);
      SpringFontCharacter springFontCharacter35 = new SpringFontCharacter('Ｂ', new Rectangle(325, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter35.Character, springFontCharacter35);
      SpringFontCharacter springFontCharacter36 = new SpringFontCharacter('Ｃ', new Rectangle(335, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter36.Character, springFontCharacter36);
      SpringFontCharacter springFontCharacter37 = new SpringFontCharacter('Ｄ', new Rectangle(345, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter37.Character, springFontCharacter37);
      SpringFontCharacter springFontCharacter38 = new SpringFontCharacter('Ｅ', new Rectangle(355, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter38.Character, springFontCharacter38);
      SpringFontCharacter springFontCharacter39 = new SpringFontCharacter('Ｆ', new Rectangle(365, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter39.Character, springFontCharacter39);
      SpringFontCharacter springFontCharacter40 = new SpringFontCharacter('Ｇ', new Rectangle(375, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter40.Character, springFontCharacter40);
      SpringFontCharacter springFontCharacter41 = new SpringFontCharacter('Ｈ', new Rectangle(385, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter41.Character, springFontCharacter41);
      SpringFontCharacter springFontCharacter42 = new SpringFontCharacter('Ｉ', new Rectangle(395, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter42.Character, springFontCharacter42);
      SpringFontCharacter springFontCharacter43 = new SpringFontCharacter('Ｊ', new Rectangle(402, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter43.Character, springFontCharacter43);
      SpringFontCharacter springFontCharacter44 = new SpringFontCharacter('Ｋ', new Rectangle(412, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter44.Character, springFontCharacter44);
      SpringFontCharacter springFontCharacter45 = new SpringFontCharacter('Ｌ', new Rectangle(422, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter45.Character, springFontCharacter45);
      SpringFontCharacter springFontCharacter46 = new SpringFontCharacter('Ｍ', new Rectangle(432, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter46.Character, springFontCharacter46);
      SpringFontCharacter springFontCharacter47 = new SpringFontCharacter('Ｎ', new Rectangle(442, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter47.Character, springFontCharacter47);
      SpringFontCharacter springFontCharacter48 = new SpringFontCharacter('Ｏ', new Rectangle(452, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter48.Character, springFontCharacter48);
      SpringFontCharacter springFontCharacter49 = new SpringFontCharacter('Ｐ', new Rectangle(462, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter49.Character, springFontCharacter49);
      SpringFontCharacter springFontCharacter50 = new SpringFontCharacter('Ｑ', new Rectangle(472, 1, 10, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter50.Character, springFontCharacter50);
      SpringFontCharacter springFontCharacter51 = new SpringFontCharacter('Ｒ', new Rectangle(483, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter51.Character, springFontCharacter51);
      SpringFontCharacter springFontCharacter52 = new SpringFontCharacter('Ｓ', new Rectangle(493, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter52.Character, springFontCharacter52);
      SpringFontCharacter springFontCharacter53 = new SpringFontCharacter('Ｔ', new Rectangle(503, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter53.Character, springFontCharacter53);
      SpringFontCharacter springFontCharacter54 = new SpringFontCharacter('Ｕ', new Rectangle(513, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter54.Character, springFontCharacter54);
      SpringFontCharacter springFontCharacter55 = new SpringFontCharacter('Ｖ', new Rectangle(523, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter55.Character, springFontCharacter55);
      SpringFontCharacter springFontCharacter56 = new SpringFontCharacter('Ｗ', new Rectangle(533, 1, 9, 19), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter56.Character, springFontCharacter56);
      SpringFontCharacter springFontCharacter57 = new SpringFontCharacter('Ｘ', new Rectangle(543, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter57.Character, springFontCharacter57);
      SpringFontCharacter springFontCharacter58 = new SpringFontCharacter('Ｙ', new Rectangle(553, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter58.Character, springFontCharacter58);
      SpringFontCharacter springFontCharacter59 = new SpringFontCharacter('Ｚ', new Rectangle(563, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter59.Character, springFontCharacter59);
      SpringFontCharacter springFontCharacter60 = new SpringFontCharacter('［', new Rectangle(573, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter60.Character, springFontCharacter60);
      SpringFontCharacter springFontCharacter61 = new SpringFontCharacter('＼', new Rectangle(580, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter61.Character, springFontCharacter61);
      SpringFontCharacter springFontCharacter62 = new SpringFontCharacter('］', new Rectangle(590, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter62.Character, springFontCharacter62);
      SpringFontCharacter springFontCharacter63 = new SpringFontCharacter('＾', new Rectangle(597, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter63.Character, springFontCharacter63);
      SpringFontCharacter springFontCharacter64 = new SpringFontCharacter('＿', new Rectangle(607, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter64.Character, springFontCharacter64);
      SpringFontCharacter springFontCharacter65 = new SpringFontCharacter('｀', new Rectangle(617, 1, 5, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter65.Character, springFontCharacter65);
      SpringFontCharacter springFontCharacter66 = new SpringFontCharacter('ａ', new Rectangle(623, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter66.Character, springFontCharacter66);
      SpringFontCharacter springFontCharacter67 = new SpringFontCharacter('ｂ', new Rectangle(633, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter67.Character, springFontCharacter67);
      SpringFontCharacter springFontCharacter68 = new SpringFontCharacter('ｃ', new Rectangle(643, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter68.Character, springFontCharacter68);
      SpringFontCharacter springFontCharacter69 = new SpringFontCharacter('ｄ', new Rectangle(653, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter69.Character, springFontCharacter69);
      SpringFontCharacter springFontCharacter70 = new SpringFontCharacter('ｅ', new Rectangle(663, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter70.Character, springFontCharacter70);
      SpringFontCharacter springFontCharacter71 = new SpringFontCharacter('ｆ', new Rectangle(673, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter71.Character, springFontCharacter71);
      SpringFontCharacter springFontCharacter72 = new SpringFontCharacter('ｇ', new Rectangle(683, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter72.Character, springFontCharacter72);
      SpringFontCharacter springFontCharacter73 = new SpringFontCharacter('ｈ', new Rectangle(693, 1, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter73.Character, springFontCharacter73);
      SpringFontCharacter springFontCharacter74 = new SpringFontCharacter('ｉ', new Rectangle(703, 1, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter74.Character, springFontCharacter74);
      SpringFontCharacter springFontCharacter75 = new SpringFontCharacter('ｊ', new Rectangle(710, 1, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter75.Character, springFontCharacter75);
      SpringFontCharacter springFontCharacter76 = new SpringFontCharacter('ｋ', new Rectangle(1, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter76.Character, springFontCharacter76);
      SpringFontCharacter springFontCharacter77 = new SpringFontCharacter('ｌ', new Rectangle(11, 22, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter77.Character, springFontCharacter77);
      SpringFontCharacter springFontCharacter78 = new SpringFontCharacter('ｍ', new Rectangle(18, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter78.Character, springFontCharacter78);
      SpringFontCharacter springFontCharacter79 = new SpringFontCharacter('ｎ', new Rectangle(28, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter79.Character, springFontCharacter79);
      SpringFontCharacter springFontCharacter80 = new SpringFontCharacter('ｏ', new Rectangle(38, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter80.Character, springFontCharacter80);
      SpringFontCharacter springFontCharacter81 = new SpringFontCharacter('ｐ', new Rectangle(48, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter81.Character, springFontCharacter81);
      SpringFontCharacter springFontCharacter82 = new SpringFontCharacter('ｑ', new Rectangle(58, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter82.Character, springFontCharacter82);
      SpringFontCharacter springFontCharacter83 = new SpringFontCharacter('ｒ', new Rectangle(68, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter83.Character, springFontCharacter83);
      SpringFontCharacter springFontCharacter84 = new SpringFontCharacter('ｓ', new Rectangle(78, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter84.Character, springFontCharacter84);
      SpringFontCharacter springFontCharacter85 = new SpringFontCharacter('ｔ', new Rectangle(88, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter85.Character, springFontCharacter85);
      SpringFontCharacter springFontCharacter86 = new SpringFontCharacter('ｕ', new Rectangle(98, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter86.Character, springFontCharacter86);
      SpringFontCharacter springFontCharacter87 = new SpringFontCharacter('ｖ', new Rectangle(108, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter87.Character, springFontCharacter87);
      SpringFontCharacter springFontCharacter88 = new SpringFontCharacter('ｗ', new Rectangle(118, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter88.Character, springFontCharacter88);
      SpringFontCharacter springFontCharacter89 = new SpringFontCharacter('ｘ', new Rectangle(128, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter89.Character, springFontCharacter89);
      SpringFontCharacter springFontCharacter90 = new SpringFontCharacter('ｙ', new Rectangle(138, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter90.Character, springFontCharacter90);
      SpringFontCharacter springFontCharacter91 = new SpringFontCharacter('ｚ', new Rectangle(148, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter91.Character, springFontCharacter91);
      SpringFontCharacter springFontCharacter92 = new SpringFontCharacter('｛', new Rectangle(158, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter92.Character, springFontCharacter92);
      SpringFontCharacter springFontCharacter93 = new SpringFontCharacter('｜', new Rectangle(168, 22, 14, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter93.Character, springFontCharacter93);
      SpringFontCharacter springFontCharacter94 = new SpringFontCharacter('｝', new Rectangle(183, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter94.Character, springFontCharacter94);
      SpringFontCharacter springFontCharacter95 = new SpringFontCharacter('～', new Rectangle(193, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter95.Character, springFontCharacter95);
      SpringFontCharacter springFontCharacter96 = new SpringFontCharacter('｟', new Rectangle(203, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter96.Character, springFontCharacter96);
      SpringFontCharacter springFontCharacter97 = new SpringFontCharacter('｠', new Rectangle(213, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter97.Character, springFontCharacter97);
      SpringFontCharacter springFontCharacter98 = new SpringFontCharacter('｡', new Rectangle(223, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter98.Character, springFontCharacter98);
      SpringFontCharacter springFontCharacter99 = new SpringFontCharacter('｢', new Rectangle(231, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter99.Character, springFontCharacter99);
      SpringFontCharacter springFontCharacter100 = new SpringFontCharacter('｣', new Rectangle(239, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter100.Character, springFontCharacter100);
      SpringFontCharacter springFontCharacter101 = new SpringFontCharacter('､', new Rectangle(247, 22, 3, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter101.Character, springFontCharacter101);
      SpringFontCharacter springFontCharacter102 = new SpringFontCharacter('･', new Rectangle(251, 22, 6, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter102.Character, springFontCharacter102);
      SpringFontCharacter springFontCharacter103 = new SpringFontCharacter('ｦ', new Rectangle(258, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter103.Character, springFontCharacter103);
      SpringFontCharacter springFontCharacter104 = new SpringFontCharacter('ｧ', new Rectangle(266, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter104.Character, springFontCharacter104);
      SpringFontCharacter springFontCharacter105 = new SpringFontCharacter('ｨ', new Rectangle(274, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter105.Character, springFontCharacter105);
      SpringFontCharacter springFontCharacter106 = new SpringFontCharacter('ｩ', new Rectangle(282, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter106.Character, springFontCharacter106);
      SpringFontCharacter springFontCharacter107 = new SpringFontCharacter('ｪ', new Rectangle(290, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter107.Character, springFontCharacter107);
      SpringFontCharacter springFontCharacter108 = new SpringFontCharacter('ｫ', new Rectangle(298, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter108.Character, springFontCharacter108);
      SpringFontCharacter springFontCharacter109 = new SpringFontCharacter('ｬ', new Rectangle(306, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter109.Character, springFontCharacter109);
      SpringFontCharacter springFontCharacter110 = new SpringFontCharacter('ｭ', new Rectangle(314, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter110.Character, springFontCharacter110);
      SpringFontCharacter springFontCharacter111 = new SpringFontCharacter('ｮ', new Rectangle(322, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter111.Character, springFontCharacter111);
      SpringFontCharacter springFontCharacter112 = new SpringFontCharacter('ｯ', new Rectangle(330, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter112.Character, springFontCharacter112);
      SpringFontCharacter springFontCharacter113 = new SpringFontCharacter('ｰ', new Rectangle(338, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter113.Character, springFontCharacter113);
      SpringFontCharacter springFontCharacter114 = new SpringFontCharacter('ｱ', new Rectangle(346, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter114.Character, springFontCharacter114);
      SpringFontCharacter springFontCharacter115 = new SpringFontCharacter('ｲ', new Rectangle(354, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter115.Character, springFontCharacter115);
      SpringFontCharacter springFontCharacter116 = new SpringFontCharacter('ｳ', new Rectangle(362, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter116.Character, springFontCharacter116);
      SpringFontCharacter springFontCharacter117 = new SpringFontCharacter('ｴ', new Rectangle(370, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter117.Character, springFontCharacter117);
      SpringFontCharacter springFontCharacter118 = new SpringFontCharacter('ｵ', new Rectangle(378, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter118.Character, springFontCharacter118);
      SpringFontCharacter springFontCharacter119 = new SpringFontCharacter('ｶ', new Rectangle(386, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter119.Character, springFontCharacter119);
      SpringFontCharacter springFontCharacter120 = new SpringFontCharacter('ｷ', new Rectangle(394, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter120.Character, springFontCharacter120);
      SpringFontCharacter springFontCharacter121 = new SpringFontCharacter('ｸ', new Rectangle(402, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter121.Character, springFontCharacter121);
      SpringFontCharacter springFontCharacter122 = new SpringFontCharacter('ｹ', new Rectangle(410, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter122.Character, springFontCharacter122);
      SpringFontCharacter springFontCharacter123 = new SpringFontCharacter('ｺ', new Rectangle(418, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter123.Character, springFontCharacter123);
      SpringFontCharacter springFontCharacter124 = new SpringFontCharacter('ｻ', new Rectangle(426, 22, 8, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter124.Character, springFontCharacter124);
      SpringFontCharacter springFontCharacter125 = new SpringFontCharacter('ｼ', new Rectangle(435, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter125.Character, springFontCharacter125);
      SpringFontCharacter springFontCharacter126 = new SpringFontCharacter('ｽ', new Rectangle(443, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter126.Character, springFontCharacter126);
      SpringFontCharacter springFontCharacter127 = new SpringFontCharacter('ｾ', new Rectangle(451, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter127.Character, springFontCharacter127);
      SpringFontCharacter springFontCharacter128 = new SpringFontCharacter('ｿ', new Rectangle(459, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter128.Character, springFontCharacter128);
      SpringFontCharacter springFontCharacter129 = new SpringFontCharacter('ﾀ', new Rectangle(467, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter129.Character, springFontCharacter129);
      SpringFontCharacter springFontCharacter130 = new SpringFontCharacter('ﾁ', new Rectangle(475, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter130.Character, springFontCharacter130);
      SpringFontCharacter springFontCharacter131 = new SpringFontCharacter('ﾂ', new Rectangle(483, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter131.Character, springFontCharacter131);
      SpringFontCharacter springFontCharacter132 = new SpringFontCharacter('ﾃ', new Rectangle(491, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter132.Character, springFontCharacter132);
      SpringFontCharacter springFontCharacter133 = new SpringFontCharacter('ﾄ', new Rectangle(499, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter133.Character, springFontCharacter133);
      SpringFontCharacter springFontCharacter134 = new SpringFontCharacter('ﾅ', new Rectangle(507, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter134.Character, springFontCharacter134);
      SpringFontCharacter springFontCharacter135 = new SpringFontCharacter('ﾆ', new Rectangle(515, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter135.Character, springFontCharacter135);
      SpringFontCharacter springFontCharacter136 = new SpringFontCharacter('ﾇ', new Rectangle(523, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter136.Character, springFontCharacter136);
      SpringFontCharacter springFontCharacter137 = new SpringFontCharacter('ﾈ', new Rectangle(531, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter137.Character, springFontCharacter137);
      SpringFontCharacter springFontCharacter138 = new SpringFontCharacter('ﾉ', new Rectangle(539, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter138.Character, springFontCharacter138);
      SpringFontCharacter springFontCharacter139 = new SpringFontCharacter('ﾊ', new Rectangle(547, 22, 9, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter139.Character, springFontCharacter139);
      SpringFontCharacter springFontCharacter140 = new SpringFontCharacter('ﾋ', new Rectangle(557, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter140.Character, springFontCharacter140);
      SpringFontCharacter springFontCharacter141 = new SpringFontCharacter('ﾌ', new Rectangle(565, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter141.Character, springFontCharacter141);
      SpringFontCharacter springFontCharacter142 = new SpringFontCharacter('ﾍ', new Rectangle(573, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter142.Character, springFontCharacter142);
      SpringFontCharacter springFontCharacter143 = new SpringFontCharacter('ﾎ', new Rectangle(581, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter143.Character, springFontCharacter143);
      SpringFontCharacter springFontCharacter144 = new SpringFontCharacter('ﾏ', new Rectangle(589, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter144.Character, springFontCharacter144);
      SpringFontCharacter springFontCharacter145 = new SpringFontCharacter('ﾐ', new Rectangle(597, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter145.Character, springFontCharacter145);
      SpringFontCharacter springFontCharacter146 = new SpringFontCharacter('ﾑ', new Rectangle(605, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter146.Character, springFontCharacter146);
      SpringFontCharacter springFontCharacter147 = new SpringFontCharacter('ﾒ', new Rectangle(613, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter147.Character, springFontCharacter147);
      SpringFontCharacter springFontCharacter148 = new SpringFontCharacter('ﾓ', new Rectangle(621, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter148.Character, springFontCharacter148);
      SpringFontCharacter springFontCharacter149 = new SpringFontCharacter('ﾔ', new Rectangle(629, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter149.Character, springFontCharacter149);
      SpringFontCharacter springFontCharacter150 = new SpringFontCharacter('ﾕ', new Rectangle(637, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter150.Character, springFontCharacter150);
      SpringFontCharacter springFontCharacter151 = new SpringFontCharacter('ﾖ', new Rectangle(645, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter151.Character, springFontCharacter151);
      SpringFontCharacter springFontCharacter152 = new SpringFontCharacter('ﾗ', new Rectangle(653, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter152.Character, springFontCharacter152);
      SpringFontCharacter springFontCharacter153 = new SpringFontCharacter('ﾘ', new Rectangle(661, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter153.Character, springFontCharacter153);
      SpringFontCharacter springFontCharacter154 = new SpringFontCharacter('ﾙ', new Rectangle(669, 22, 8, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter154.Character, springFontCharacter154);
      SpringFontCharacter springFontCharacter155 = new SpringFontCharacter('ﾚ', new Rectangle(678, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter155.Character, springFontCharacter155);
      SpringFontCharacter springFontCharacter156 = new SpringFontCharacter('ﾛ', new Rectangle(686, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter156.Character, springFontCharacter156);
      SpringFontCharacter springFontCharacter157 = new SpringFontCharacter('ﾜ', new Rectangle(694, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter157.Character, springFontCharacter157);
      SpringFontCharacter springFontCharacter158 = new SpringFontCharacter('ﾝ', new Rectangle(702, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter158.Character, springFontCharacter158);
      SpringFontCharacter springFontCharacter159 = new SpringFontCharacter('ﾞ', new Rectangle(710, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter159.Character, springFontCharacter159);
      SpringFontCharacter springFontCharacter160 = new SpringFontCharacter('ﾟ', new Rectangle(718, 22, 7, 20), 0.46f, _RightSpacing: -0.5f);
      FontDictionary.Add(springFontCharacter160.Character, springFontCharacter160);
    }

    public FontSet_JapaneseRoman_CJK()
    {
      this.CharacterSet = CharSet.CJK;
      this.TextureFileName = "japromancharas";
      this.startIndex = 65280;
      this.endIndex = 65439;
    }
  }
}
