// Decompiled with JetBrains decompiler
// Type: TinyZoo.GAMESTATE
// Assembly: LetsBuildAZoo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DEB7467C-E857-4369-A6B7-78A1E0037E5E
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Let's Build a Zoo Demo\LetsBuildAZoo.exe

namespace TinyZoo
{
  internal enum GAMESTATE
  {
    SplashScreenSetUp,
    SplashScreen,
    GameSettingsSetUp,
    GameSettings,
    IntroSceneSetUp,
    IntroScene,
    TitleScreenSetUp,
    TitleScreen,
    ModeSelectSetUp,
    ModeSelect,
    SettingsSetUp,
    Settings,
    GamePlaySetUp,
    GamePlay,
    OverWorldSetUp,
    OverWorld,
    RewardSetUp,
    Reward,
    IAPSCreenSetUp,
    IAPScreen,
    IAPStoreSetUp,
    IAPStore,
    ArcadeModeSetUp,
    ArcadeMode,
    CollectionViewSetUp,
    CollectionView,
    ArcadeCreditsSetUp,
    ArcadeCredits,
    ProfitLadderSetUp,
    ProfitLadder,
    RankRewardSetup,
    RankReward,
    EventViewSetUp,
    EventView,
    ExtraCashSetUp,
    ExtraCash,
    BountyResultsSetUp,
    BountyResults,
    CharacterSelectSetUp,
    CharacterSelect,
    WorldMapSetUp,
    WorldMap,
    DebugAnimalViewerSetUp,
    DebugAnimalViewer,
    NewBreedSetUp,
    NewBreed,
    ManagePenSetUp,
    ManagePen,
    ManageShopSetUp,
    ManageShop,
    TicketPriceSetUp,
    TicketPrice,
    WeekSummarySetUp,
    WeekSummary,
    ManageStoreRoomSetUp,
    ManageStoreRoom,
    ArchitectResearchSetUp,
    ArchitectResearch,
    ShelterSetUp,
    Shelter,
    BetaResultsSetUp,
    BetaResults,
    MoralitySummarySetUp,
    MoralitySummary,
    ProcessingSetUp,
    Processing,
    PhotoModeSetUp,
    PhotoMode,
    None,
  }
}
