// Decompiled with JetBrains decompiler
// Type: TinyZoo.Audio.SoundEffectType
// Assembly: LetsBuildAZoo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DEB7467C-E857-4369-A6B7-78A1E0037E5E
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Let's Build a Zoo Demo\LetsBuildAZoo.exe

namespace TinyZoo.Audio
{
  internal enum SoundEffectType
  {
    Menu_Splash,
    ConfirmClick,
    BackClick,
    MenuOpen,
    MenuClose,
    ConfirmUpgrade,
    DeathChargeDown,
    FieldConnect,
    LaunchBeam,
    ClickSingle,
    Unbuild,
    BuildSomething,
    DemolishBuilding,
    Explode,
    KillPerson,
    BeamConnect,
    ModeSelectButton,
    Rotate,
    ForestAmbience,
    Gun,
    Build_Paint,
    Stamp,
    Rabbit_Cute01,
    Rabbit_Cute02,
    Rabbit_Cute03,
    Rabbit_LessCute01,
    Rabbit_LessCute02,
    Rabbit_LessCute03,
    Rabbit_Tiny,
    Rabbit_Tiny2,
    Goose_Buck01,
    Goose_Buck02,
    Goose_Buck03,
    Goose_Buck04,
    Goose_Buck05,
    Goose_Buck06,
    Goose_Call01,
    Goose_Call02,
    Goose_Call03,
    Goose_Call04,
    Goose_Call05,
    Goose_Call06,
    Goose_Honk01,
    Goose_Honk02,
    Goose_Honk03,
    Goose_Honk04,
    Goose_Honk05,
    Goose_Honk06,
    Goose_Honk07,
    Goose_Honk08,
    Goose_Honk09,
    Goose_Honk10,
    Goose_Honk11,
    Goose_SmallHonk01,
    Goose_SmallHonk02,
    Goose_SmallHonk03,
    Goose_SmallHonk04,
    Goose_SmallHonk05,
    Goose_SmallHonk06,
    None,
  }
}
