// Decompiled with JetBrains decompiler
// Type: TinyZoo.Z_Corruption.CorruptionData
// Assembly: LetsBuildAZoo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DEB7467C-E857-4369-A6B7-78A1E0037E5E
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Let's Build a Zoo Demo\LetsBuildAZoo.exe

using TinyZoo.Tile_Data;

namespace TinyZoo.Z_Corruption
{
  internal class CorruptionData
  {
    internal static TILETYPE GetTileToCorruption(TILETYPE tiletype, bool IsFloor)
    {
      if (IsFloor)
      {
        switch (tiletype)
        {
          case TILETYPE.Floor_GreenGrass:
            return TILETYPE.CorruptedGreenGrass_Floor;
          case TILETYPE.Floor_Dirt:
            return TILETYPE.CorruptedDirt_Floor;
          case TILETYPE.Floor_RedCircles:
            return TILETYPE.Floor_RedCircles;
          case TILETYPE.Floor_GreyBricks:
            return TILETYPE.Floor_GreyBricks;
          case TILETYPE.Grasslands_Floor:
            return TILETYPE.CorruptedGrass_Floor;
          case TILETYPE.Forest_Floor:
            return TILETYPE.CorruptedForest_Floor;
          case TILETYPE.Savanah_Floor:
            return TILETYPE.CorruptedSavanah_Floor;
          case TILETYPE.Desert_Floor:
            return TILETYPE.CorruptedDesert_Floor;
          case TILETYPE.Mountain_Floor:
            return TILETYPE.CorruptedMountain_Floor;
          case TILETYPE.Arctic_Floor:
            return TILETYPE.CorruptedArctic_Floor;
          case TILETYPE.Tropical_Floor:
            return TILETYPE.CorruptedTropical_Floor;
          case TILETYPE.Floor_OrangeTiles:
            return TILETYPE.Floor_OrangeTiles;
          case TILETYPE.Floor_ColorfulBrickTile:
            return TILETYPE.Floor_ColorfulBrickTile;
          case TILETYPE.Floor_BlueCircleTiles:
            return TILETYPE.Floor_BlueCircleTiles;
          case TILETYPE.Floor_WoodenBoards:
            return TILETYPE.Floor_WoodenBoards;
          case TILETYPE.Floor_MetalDecoTile:
            return TILETYPE.Floor_MetalDecoTile;
          case TILETYPE.Floor_PawDecoTile:
            return TILETYPE.Floor_PawDecoTile;
          case TILETYPE.Floor_Cobblestone:
            return TILETYPE.Floor_Cobblestone;
          case TILETYPE.Floor_PinkSmallTiles:
            return TILETYPE.Floor_PinkSmallTiles;
          case TILETYPE.Floor_BrownOctoTile:
            return TILETYPE.Floor_BrownOctoTile;
          case TILETYPE.Floor_GreenAndBlueDiamondTile:
            return TILETYPE.Floor_GreenAndBlueDiamondTile;
          case TILETYPE.Floor_BrownSquareTile:
            return TILETYPE.Floor_BrownSquareTile;
          case TILETYPE.Floor_Snow:
            return TILETYPE.CorruptedSnow_Floor;
          case TILETYPE.Volume_RedPathway:
            return TILETYPE.Volume_RedPathway;
          case TILETYPE.Volume_Grass:
          case TILETYPE.Volume_DarkGrass:
          case TILETYPE.Volume_YellowGrass:
          case TILETYPE.Volume_LightGrass:
            return TILETYPE.CorruptedDirtGrass_Volume;
          case TILETYPE.Volume_WoodenBoards:
            return TILETYPE.Volume_WoodenBoards;
          case TILETYPE.Floor_WoodenPlanks:
            return TILETYPE.Floor_WoodenPlanks;
          case TILETYPE.Floor_WoodenTrunk:
            return TILETYPE.Floor_WoodenTrunk;
          case TILETYPE.Floor_StonePebbles:
            return TILETYPE.Floor_StonePebbles;
          case TILETYPE.Volume_WhiteSnow:
            return TILETYPE.CorruptedSnow_Volume;
          case TILETYPE.Volume_Water:
            return TILETYPE.Volume_Water;
          case TILETYPE.Volume_WoodenBridge:
            return TILETYPE.Volume_WoodenBridge;
          case TILETYPE.Volume_Sand:
            return TILETYPE.CorruptedSand_Volume;
          case TILETYPE.AztacTempleFloor:
            return TILETYPE.AztacTempleFloor;
          case TILETYPE.Volume_LightMud:
            return TILETYPE.CorruptedDirtFloor_Volume;
          default:
            return TILETYPE.CorruptedDirtTile;
        }
      }
      else
      {
        switch (tiletype)
        {
          case TILETYPE.Grasslands_WallCorner:
            return TILETYPE.CorruptedGrass_WallCorner;
          case TILETYPE.Grasslands_WallSide:
            return TILETYPE.CorruptedGrass_WallSide;
          case TILETYPE.Forest_WallCorner:
            return TILETYPE.CorruptedForest_WallCorner;
          case TILETYPE.Savanah_WallCorner:
            return TILETYPE.CorruptedSavanah_WallCorner;
          case TILETYPE.Desert_WallCorner:
            return TILETYPE.CorruptedDesert_WallCorner;
          case TILETYPE.Mountain_WallCorner:
            return TILETYPE.CorruptedMountain_WallCorner;
          case TILETYPE.Arctic_WallCorner:
            return TILETYPE.CorruptedArctic_WallCorner;
          case TILETYPE.Tropical_WallCorner:
            return TILETYPE.CorruptedTropical_WallCorner;
          case TILETYPE.Forest_WallSide:
            return TILETYPE.CorruptedForest_WallSide;
          case TILETYPE.Savanah_WallSide:
            return TILETYPE.CorruptedSavanah_WallSide;
          case TILETYPE.Desert_WallSide:
            return TILETYPE.CorruptedDesert_WallSide;
          case TILETYPE.Mountain_WallSide:
            return TILETYPE.CorruptedMountain_WallSide;
          case TILETYPE.Arctic_WallSide:
            return TILETYPE.CorruptedArctic_WallSide;
          case TILETYPE.Tropical_WallSide:
            return TILETYPE.CorruptedTropical_WallSide;
          case TILETYPE.PlantPot:
            return TILETYPE.CorruptedPlantPot;
          case TILETYPE.RedFlag:
            return TILETYPE.RedFlag;
          case TILETYPE.RoundFountain:
            return TILETYPE.RoundFountain;
          case TILETYPE.FlowerPatch:
          case TILETYPE.RedFlower:
          case TILETYPE.WhiteFlower:
          case TILETYPE.PurpleFlower:
          case TILETYPE.PurpleFlowerPatch:
          case TILETYPE.DarkSmallPlant:
            return TILETYPE.CorruptedBushSmall;
          case TILETYPE.SmallDesertRockDeco:
            return TILETYPE.SmallDesertRockDeco;
          case TILETYPE.DesertRockDeco:
            return TILETYPE.DesertRockDeco;
          case TILETYPE.WoodenToilet:
            return TILETYPE.CorruptedWoodenToilet;
          case TILETYPE.BigTree:
          case TILETYPE.ZooTree:
            return TILETYPE.CorruptedZooTree;
          case TILETYPE.PottedPlant:
            return TILETYPE.CorruptedPottedPlant;
          case TILETYPE.ElephantFountain:
            return TILETYPE.ElephantFountain;
          case TILETYPE.Grasslands_WallInnerCorner:
            return TILETYPE.CorruptedGrass_WallInnerCorner;
          case TILETYPE.Forest_WallInnerCorner:
            return TILETYPE.CorruptedForest_WallInnerCorner;
          case TILETYPE.Savanah_WallInnerCorner:
            return TILETYPE.CorruptedSavanah_WallInnerCorner;
          case TILETYPE.Desert_WallInnerCorner:
            return TILETYPE.CorruptedDesert_WallInnerCorner;
          case TILETYPE.Mountain_WallInnerCorner:
            return TILETYPE.CorruptedMountain_WallInnerCorner;
          case TILETYPE.Arctic_WallInnerCorner:
            return TILETYPE.CorruptedArctic_WallInnerCorner;
          case TILETYPE.Tropical_WallInnerCorner:
            return TILETYPE.CorruptedTropical_WallInnerCorner;
          case TILETYPE.ElephantMarbleFountain:
            return TILETYPE.CorruptedElephantMarbleFountain;
          case TILETYPE.FlamingoHedge:
            return TILETYPE.CorruptedFlamingoHedge;
          case TILETYPE.GiraffeHedge:
            return TILETYPE.CorruptedGiraffeHedge;
          case TILETYPE.ElephantHedge:
            return TILETYPE.CorruptedElephantHedge;
          case TILETYPE.MonkeyStatue:
            return TILETYPE.MonkeyStatue;
          case TILETYPE.GiantSunFlower:
            return TILETYPE.CorruptedGiantSunFlower;
          case TILETYPE.ZooStandee:
            return TILETYPE.ZooStandee;
          case TILETYPE.PenguinStandee:
            return TILETYPE.PenguinStandee;
          case TILETYPE.BearStandee:
            return TILETYPE.BearStandee;
          case TILETYPE.MonkeyBanner:
            return TILETYPE.MonkeyBanner;
          case TILETYPE.SakuraTree:
          case TILETYPE.PineTree:
          case TILETYPE.ColoredTree:
          case TILETYPE.IcyTree:
          case TILETYPE.DeadWinterTree:
          case TILETYPE.LightGreenTree:
            return TILETYPE.CorruptedTree;
          case TILETYPE.RockElephant:
            return TILETYPE.RockElephant;
          case TILETYPE.SealStandee:
            return TILETYPE.SealStandee;
          case TILETYPE.OwlClock:
            return TILETYPE.OwlClock;
          case TILETYPE.HeShee:
            return TILETYPE.HeShee;
          case TILETYPE.Totem:
            return TILETYPE.Totem;
          case TILETYPE.WoodenTotem:
            return TILETYPE.WoodenTotem;
          case TILETYPE.Gate_Grass:
            return TILETYPE.CorruptedGrass_Gate;
          case TILETYPE.Gate_Forest:
            return TILETYPE.CorruptedForest_Gate;
          case TILETYPE.Gate_Savanah:
            return TILETYPE.CorruptedSavanah_Gate;
          case TILETYPE.Gate_Desert:
            return TILETYPE.CorruptedDesert_Gate;
          case TILETYPE.Gate_Mountain:
            return TILETYPE.CorruptedMountain_Gate;
          case TILETYPE.Gate_Arctic:
            return TILETYPE.CorruptedArctic_Gate;
          case TILETYPE.Gate_Tropical:
            return TILETYPE.CorruptedTropical_Gate;
          case TILETYPE.PalmTree:
            return TILETYPE.CorruptedPalmTree;
          case TILETYPE.GreenTree:
          case TILETYPE.DeadTree:
            return TILETYPE.CorruptedDeadTree;
          case TILETYPE.IrisPlantPot:
            return TILETYPE.CorruptedIrisPlantPot;
          case TILETYPE.YellowPlantPot:
            return TILETYPE.CorruptedYellowPlantPot;
          case TILETYPE.BonsaiPlantPot:
            return TILETYPE.CorruptedBonsaiPlantPot;
          case TILETYPE.Ferns:
            return TILETYPE.CorruptedFerns;
          case TILETYPE.SmallRock:
            return TILETYPE.SmallRock;
          case TILETYPE.MediumRock:
            return TILETYPE.MediumRock;
          case TILETYPE.LargeMossyRock:
            return TILETYPE.CorruptedLargeMossyRock;
          case TILETYPE.MiniFountain:
            return TILETYPE.MiniFountain;
          case TILETYPE.ElegantTallFountain:
            return TILETYPE.ElegantTallFountain;
          case TILETYPE.HedgeArchYellowFlowers:
          case TILETYPE.HedgeArchWhiteFlowers:
          case TILETYPE.JungleArch:
            return TILETYPE.CorruptedJungleArch;
          case TILETYPE.WhiteMetalVineArch:
            return TILETYPE.CorruptedWhiteMetalVineArch;
          case TILETYPE.BlackMetalRoseArch:
            return TILETYPE.CorruptedBlackMetalRoseArch;
          case TILETYPE.PeacockBush:
            return TILETYPE.CorruptedPeacockBush;
          case TILETYPE.IglooToilet:
            return TILETYPE.CorruptedIglooToilet;
          case TILETYPE.Cactus:
            return TILETYPE.CorruptedCactus;
          case TILETYPE.IceArch:
            return TILETYPE.CorruptedIceArch;
          case TILETYPE.SmallIceRocks:
            return TILETYPE.CorruptedSmallIceRocks;
          case TILETYPE.ThinIceRocks:
            return TILETYPE.CorruptedThinIceRocks;
          case TILETYPE.IceCrystals:
            return TILETYPE.CorruptedIceCrystals;
          case TILETYPE.Snowman:
            return TILETYPE.CorruptedSnowman;
          case TILETYPE.LionSnowSculpture:
            return TILETYPE.CorruptedLionSnowSculpture;
          case TILETYPE.SealIceSculpture:
            return TILETYPE.CorruptedSealIceSculpture;
          case TILETYPE.DeerIceSculpture:
            return TILETYPE.CorruptedDeerIceSculpture;
          case TILETYPE.BearIceSculpture:
            return TILETYPE.CorruptedBearIceSculpture;
          case TILETYPE.BirdIceSculpture:
            return TILETYPE.CorruptedBirdIceSculpture;
          case TILETYPE.GiraffeIceSculpture:
            return TILETYPE.CorruptedGiraffeIceSculpture;
          case TILETYPE.IceShelter:
            return TILETYPE.CorruptedIceShelter;
          case TILETYPE.ZooIceSign:
            return TILETYPE.CorruptedZooIceSign;
          case TILETYPE.IceCastle:
            return TILETYPE.CorruptedIceCastle;
          case TILETYPE.IceChair:
            return TILETYPE.CorruptedIceChair;
          case TILETYPE.GiantTree:
            return TILETYPE.CorruptedGiantTree;
          case TILETYPE.ZooRockSign:
            return TILETYPE.CorruptedZooRockSign;
          case TILETYPE.GiantPigBalloon:
            return TILETYPE.GiantPigBalloon;
          case TILETYPE.Bamboo:
            return TILETYPE.CorruptedBamboo;
          case TILETYPE.WaterTower:
            return TILETYPE.WaterTower;
          case TILETYPE.Cart:
            return TILETYPE.Cart;
          case TILETYPE.WantedPoster:
            return TILETYPE.WantedPoster;
          case TILETYPE.BigRocks:
            return TILETYPE.BigRocks;
          case TILETYPE.Pyramid:
            return TILETYPE.Pyramid;
          case TILETYPE.SandTower:
            return TILETYPE.SandTower;
          case TILETYPE.SmallPyramid:
            return TILETYPE.SmallPyramid;
          case TILETYPE.Sphinx:
            return TILETYPE.Sphinx;
          case TILETYPE.PalmTreesTall:
            return TILETYPE.CorruptedPalmTreesTall;
          case TILETYPE.Anubis:
            return TILETYPE.Anubis;
          case TILETYPE.WesternWindmill:
            return TILETYPE.WesternWindmill;
          case TILETYPE.JungleToliet:
            return TILETYPE.CorruptedJungleToliet;
          case TILETYPE.TreeLogBench:
            return TILETYPE.CorruptedTreeLogBench;
          case TILETYPE.TreeStump:
            return TILETYPE.CorruptedTreeStump;
          case TILETYPE.GlowingPlant:
            return TILETYPE.CorruptedGlowingPlant;
          case TILETYPE.RedMushrooms:
            return TILETYPE.CorruptedRedMushrooms;
          case TILETYPE.BrownMushrooms:
            return TILETYPE.CorruptedBrownMushrooms;
          case TILETYPE.LeafyFern:
            return TILETYPE.CorruptedLeafyFern;
          case TILETYPE.LargeFern:
            return TILETYPE.CorruptedLargeFern;
          case TILETYPE.TreeWithVines:
            return TILETYPE.CorruptedTreeWithVines;
          case TILETYPE.TreeSwing:
            return TILETYPE.CorruptedTreeSwing;
          case TILETYPE.JungleWaterfall:
            return TILETYPE.CorruptedJungleWaterfall;
          case TILETYPE.RockyWaterfall:
            return TILETYPE.RockyWaterfall;
          case TILETYPE.GiantBearBalloon:
            return TILETYPE.GiantBearBalloon;
          case TILETYPE.LightHouse:
            return TILETYPE.LightHouse;
          case TILETYPE.GiraffeAirDancer:
            return TILETYPE.GiraffeAirDancer;
          case TILETYPE.SnakeAirDancer:
            return TILETYPE.SnakeAirDancer;
          case TILETYPE.Caravan:
            return TILETYPE.Caravan;
          case TILETYPE.WestBarrel:
            return TILETYPE.WestBarrel;
          case TILETYPE.WestWoodenBox:
            return TILETYPE.WestWoodenBox;
          case TILETYPE.WesternArch:
            return TILETYPE.WesternArch;
          case TILETYPE.OrangeStoneArch:
            return TILETYPE.OrangeStoneArch;
          case TILETYPE.BoneArch:
            return TILETYPE.BoneArch;
          case TILETYPE.BoneDeco:
            return TILETYPE.BoneDeco;
          case TILETYPE.SmallGrass:
            return TILETYPE.CorruptedSmallGrass;
          case TILETYPE.TreeWithLights:
            return TILETYPE.CorruptedTreeWithLights;
          case TILETYPE.CarpStreamers:
            return TILETYPE.CarpStreamers;
          case TILETYPE.HorizonValleyZooBalloon:
            return TILETYPE.HorizonValleyZooBalloon;
          case TILETYPE.PineTreeDark:
            return TILETYPE.CorruptedPineTreeDark;
          case TILETYPE.ArticBush:
            return TILETYPE.CorruptedArticBush;
          case TILETYPE.TallRoofHouse:
            return TILETYPE.TallRoofHouse;
          case TILETYPE.DesertTree:
            return TILETYPE.CorruptedDesertTree;
          case TILETYPE.CactusLong:
            return TILETYPE.CorruptedCactusLong;
          case TILETYPE.AztacSnakeStatue:
            return TILETYPE.AztacSnakeStatue;
          case TILETYPE.AztacTemple:
            return TILETYPE.CorruptedAztacTemple;
          case TILETYPE.BigMountainRocks:
            return TILETYPE.BigMountainRocks;
          case TILETYPE.OrangeLargeRocks:
            return TILETYPE.OrangeLargeRocks;
          case TILETYPE.AztacTempleGate:
            return TILETYPE.AztacTempleGate;
          case TILETYPE.AsianGate:
            return TILETYPE.AsianGate;
          case TILETYPE.RockyZooSign:
            return TILETYPE.RockyZooSign;
          case TILETYPE.MediumStones:
            return TILETYPE.MediumStones;
          case TILETYPE.HotAirBalloonRide:
            return TILETYPE.CorruptedHotAirBalloonRide;
          default:
            return TILETYPE.CorruptedBush;
        }
      }
    }
  }
}
